# Generated by Django 4.2.30 on 2026-06-08 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(help_text='Se guarda por si se elimina el tour', max_length=120, verbose_name='Nombre del tour')),
                ('travel_date', models.DateField(verbose_name='Fecha del viaje')),
                ('num_people', models.PositiveIntegerField(default=1, verbose_name='Número de personas')),
                ('language', models.CharField(default='Español', max_length=30, verbose_name='Idioma del tour')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=12, verbose_name='Estado')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio total (MXN)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas / peticiones especiales')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas internas admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['-travel_date'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del tour')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('duration', models.CharField(help_text='Ej: 90 minutos, 2 días', max_length=50, verbose_name='Duración')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base (MXN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Cliente'), ('admin', 'Administrador')], default='client', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('nationality', models.CharField(blank=True, max_length=60, verbose_name='Nacionalidad')),
                ('language', models.CharField(blank=True, max_length=30, verbose_name='Idioma preferido')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas (solo admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('voucher', 'Voucher de reservación'), ('invoice', 'Factura'), ('itinerary', 'Itinerario'), ('other', 'Otro')], default='voucher', max_length=12, verbose_name='Tipo de documento')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.booking', verbose_name='Reservación')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.tour', verbose_name='Tour'),
        ),
    ]
